// EMT / paramedic training programs in South Carolina — public contact info for outreach.
// Sources: college websites, SC DPH approved training institutions list.

export const EMT_LEADS = [
  {
    id: "mtc-cce",
    name: "Midlands Technical College — EMS Programs",
    city: "Columbia, SC",
    distance: "~15 mi from Blythewood",
    type: "Community College",
    contact: "Corporate & Continuing Education",
    phone: "803-732-0432",
    email: "cce@midlandstech.edu",
    altEmail: "ems@midlandstech.edu",
    notes: "Primary EMT & paramedic training in the Columbia metro. Good fit for stretchers, boards, and training manikins.",
    url: "https://www.midlandstech.edu/programs-and-courses/health-care/emergency-medical-technician",
  },
  {
    id: "richland-ems",
    name: "Richland County EMS — EMT Academy",
    city: "Columbia, SC",
    distance: "~12 mi",
    type: "County EMS Academy",
    contact: "Training Academy",
    phone: "803-576-3400",
    email: "",
    notes: "Paid EMT academy for new hires. May purchase training equipment for hands-on labs.",
    url: "https://www.richlandcountysc.gov/Government/Jobs/Public-Safety-Careers/Emergency-Medical-Technician-EMT-Academy",
  },
  {
    id: "trident-emt",
    name: "Trident Technical College — Emergency Medical Technology",
    city: "Charleston, SC",
    distance: "~110 mi",
    type: "Community College",
    contact: "Health Sciences Admissions",
    phone: "843-574-6460",
    email: "infocenter@tridenttech.edu",
    altEmail: "lauren.leedy@tridenttech.edu",
    notes: "CAAHEP-accredited paramedic program. High demand for skills-lab equipment.",
    url: "https://www.tridenttech.edu/landing/paramedic.html",
  },
  {
    id: "tctc-ems",
    name: "Tri-County Technical College — EMT/Paramedic",
    city: "Pendleton, SC",
    distance: "~130 mi",
    type: "Community College",
    contact: "EMS Program",
    phone: "864-646-1500",
    email: "rnix@tctc.edu",
    notes: "Upstate SC program director contact listed publicly. Ask about surplus training gear.",
    url: "https://www.tctc.edu",
  },
  {
    id: "hgtc-emt",
    name: "Horry-Georgetown Technical College — EMT-Paramedic",
    city: "Conway, SC",
    distance: "~140 mi",
    type: "Community College",
    contact: "Chris Schierer, Program",
    phone: "843-477-2188",
    email: "",
    notes: "Coastal SC paramedic certificate program. Contact program chair for equipment needs.",
    url: "https://www.hgtc.edu/academics/academic-departments/emt-associated-health-sciences/emergency-medical-technology-paramedic.html",
  },
  {
    id: "greenville-tech",
    name: "Greenville Technical College — EMS",
    city: "Greenville, SC",
    distance: "~100 mi",
    type: "Community College",
    contact: "Health Sciences",
    phone: "864-250-8000",
    email: "admissions@gvltec.edu",
    notes: "Large upstate health sciences division. Often needs expired-but-usable gear for skills labs.",
    url: "https://www.gvltec.edu",
  },
  {
    id: "york-tech",
    name: "York Technical College — EMS",
    city: "Rock Hill, SC",
    distance: "~45 mi",
    type: "Community College",
    contact: "Health Programs",
    phone: "803-327-8000",
    email: "ask@yorktech.edu",
    notes: "Near Charlotte metro. EMT program; good regional buyer for radios and O2 gear.",
    url: "https://www.yorktech.edu",
  },
  {
    id: "cctc",
    name: "Central Carolina Technical College — EMS",
    city: "Sumter, SC",
    distance: "~35 mi",
    type: "Community College",
    contact: "Health Sciences",
    phone: "803-778-1961",
    email: "info@cctech.edu",
    notes: "Central SC training programs. Worth cold-emailing about surplus ambulance supplies.",
    url: "https://www.cctech.edu",
  },
  {
    id: "fdtc",
    name: "Florence-Darlington Technical College — EMS",
    city: "Florence, SC",
    distance: "~80 mi",
    type: "Community College",
    contact: "Health Sciences",
    phone: "843-661-8324",
    email: "info@fdtc.edu",
    notes: "Pee Dee region EMT training. Training departments often buy used equipment cheap.",
    url: "https://www.fdtc.edu",
  },
  {
    id: "sc-dph-ems",
    name: "SC Dept of Public Health — EMS & Trauma",
    city: "Columbia, SC",
    distance: "Statewide",
    type: "State Agency",
    contact: "EMS and Trauma Section",
    phone: "803-545-1090",
    email: "emscertifications@dph.sc.gov",
    notes: "Can point you to all DPH-approved EMT training institutions statewide via LMS portal.",
    url: "https://dph.sc.gov/professionals/healthcare-quality/ems-and-trauma/emt-certification-links",
  },
  {
    id: "sc-ems-assoc",
    name: "South Carolina EMS Association",
    city: "Statewide",
    distance: "Statewide",
    type: "Professional Association",
    contact: "SC EMS Association",
    phone: "",
    email: "",
    notes: "Industry association — good for networking with training officers who buy surplus gear.",
    url: "https://www.scemsassociation.org",
  },
  {
    id: "lowcountry-regional",
    name: "Lowcountry Regional EMS Council",
    city: "Charleston area",
    distance: "~110 mi",
    type: "Regional EMS Council",
    contact: "Education & Training",
    phone: "",
    email: "",
    notes: "Offers EMT courses with Trident Tech. Regional training coordinators buy lab equipment.",
    url: "https://www.charlestoncounty.gov/departments/ems/education-training.php",
  },
];
