// EMT / paramedic training programs in South Carolina — public contact info for outreach.
// Sources: college websites, SC DPH approved training institutions list, public program pages.

export const EMT_LEADS = [
  {
    id: "mtc-ems-coordinator",
    name: "Midlands Technical College — EMS Program Coordinator",
    city: "Columbia, SC",
    distance: "~15 mi from Blythewood",
    type: "Community College",
    contact: "Taylor Furnas, EMS Program Coordinator",
    phone: "803-767-0149",
    email: "taylormfurnas@midlandstech.edu",
    altEmail: "mccollumb@midlandstech.edu",
    notes: "Closest buyer. Program coordinator + EMS director (Benjamin McCollum) listed publicly for EMT courses.",
    url: "https://www.midlandstech.edu/programs-and-courses/health-care/emergency-medical-technician",
    priority: 1,
  },
  {
    id: "mtc-cce",
    name: "Midlands Technical College — Corporate & Continuing Education",
    city: "Columbia, SC",
    distance: "~15 mi",
    type: "Community College",
    contact: "Corporate & Continuing Education",
    phone: "803-732-0432",
    email: "cce@midlandstech.edu",
    altEmail: "ems@midlandstech.edu",
    notes: "CCE / EMS general inboxes for training certificate programs.",
    url: "https://www.midlandstech.edu/programs-and-courses/health-care/emergency-medical-technician",
    priority: 1,
  },
  {
    id: "york-tech",
    name: "York Technical College — Health Programs / EMS",
    city: "Rock Hill, SC",
    distance: "~45 mi",
    type: "Community College",
    contact: "Health Programs",
    phone: "803-327-8000",
    email: "ask@yorktech.edu",
    notes: "Near Charlotte metro. Good regional fit for training gear and radios.",
    url: "https://www.yorktech.edu",
    priority: 2,
  },
  {
    id: "cctc",
    name: "Central Carolina Technical College — Health Sciences / EMS",
    city: "Sumter, SC",
    distance: "~35 mi",
    type: "Community College",
    contact: "Health Sciences",
    phone: "803-778-1961",
    email: "info@cctech.edu",
    notes: "Central SC — short drive from Blythewood for pickup.",
    url: "https://www.cctech.edu",
    priority: 2,
  },
  {
    id: "richland-ems",
    name: "Richland County EMS — EMT Academy",
    city: "Columbia, SC",
    distance: "~12 mi",
    type: "County EMS Academy",
    contact: "Training Academy",
    phone: "803-576-3400",
    email: "",
    notes: "No public email — call. Paid EMT academy may buy lab equipment.",
    url: "https://www.richlandcountysc.gov/Government/Jobs/Public-Safety-Careers/Emergency-Medical-Technician-EMT-Academy",
    priority: 1,
  },
  {
    id: "trident-emt",
    name: "Trident Technical College — Emergency Medical Technology",
    city: "Charleston, SC",
    distance: "~110 mi",
    type: "Community College",
    contact: "Health Sciences Admissions",
    phone: "843-574-6460",
    email: "infocenter@tridenttech.edu",
    altEmail: "lauren.leedy@tridenttech.edu",
    notes: "CAAHEP-accredited paramedic program — skills labs need equipment.",
    url: "https://www.tridenttech.edu/landing/paramedic.html",
    priority: 2,
  },
  {
    id: "tctc-ems",
    name: "Tri-County Technical College — EMT/Paramedic",
    city: "Pendleton, SC",
    distance: "~130 mi",
    type: "Community College",
    contact: "EMS Program",
    phone: "864-646-1500",
    email: "rnix@tctc.edu",
    notes: "Upstate program contact listed publicly.",
    url: "https://www.tctc.edu",
    priority: 3,
  },
  {
    id: "hgtc-emt",
    name: "Horry-Georgetown Technical College — EMT-Paramedic",
    city: "Conway, SC",
    distance: "~140 mi",
    type: "Community College",
    contact: "EMS Program (Chris Schierer)",
    phone: "843-477-2188",
    email: "",
    notes: "No reliable public email — phone outreach.",
    url: "https://www.hgtc.edu/academics/academic-departments/emt-associated-health-sciences/emergency-medical-technology-paramedic.html",
    priority: 3,
  },
  {
    id: "greenville-tech",
    name: "Greenville Technical College — EMS / Health Sciences",
    city: "Greenville, SC",
    distance: "~100 mi",
    type: "Community College",
    contact: "Admissions / Health Sciences",
    phone: "864-250-8000",
    email: "admissions@gvltec.edu",
    notes: "Large upstate health sciences division.",
    url: "https://www.gvltec.edu",
    priority: 3,
  },
  {
    id: "fdtc",
    name: "Florence-Darlington Technical College — Health Sciences",
    city: "Florence, SC",
    distance: "~80 mi",
    type: "Community College",
    contact: "Health Sciences",
    phone: "843-661-8324",
    email: "info@fdtc.edu",
    notes: "Pee Dee region EMT training.",
    url: "https://www.fdtc.edu",
    priority: 3,
  },
  {
    id: "sc-dph-ems",
    name: "SC Dept of Public Health — EMS & Trauma",
    city: "Columbia, SC",
    distance: "Statewide",
    type: "State Agency",
    contact: "EMS and Trauma Section",
    phone: "803-545-1090",
    email: "emscertifications@dph.sc.gov",
    notes: "Not a buyer — can forward to approved training institutions. Soft informational ask.",
    url: "https://dph.sc.gov/professionals/healthcare-quality/ems-and-trauma/emt-certification-links",
    priority: 4,
  },
];
